[package]
name = "kyrene-winit"
version = "0.1.0"
edition = "2021"

[dependencies]
kyrene-core = { path = "../kyrene-core" }
winit = "0.30.8"
pollster = "0.4.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
console-subscriber = "0.4.1"
